name: Tests

on:
  push:
    branches: [testes]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci

      - name: Test
        run: npm test

      - name: Lint
        run: npm run lint

      - name: Monitor de cobertura
      - uses: 5monkeys/cobertura-action@master
        with:
          path: src/test.xml
          minimum_coverage: 75
        # uses: slavcodev/coverage-monitor-action@v1
        # with:
        #   github_token: ${{ secrets.GITHUB_TOKEN }}
        #   coverage_path: '../../coverage/clover.xml'
        #   threshold_alert: 60
        #   threshold_warning: 60
        #   threshold_metric: 'statements'
